version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./Backend
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/inventorydb
      - JWT_SECRET=your_jwt_secret
      - PORT=5000
    depends_on:
      - mongo

  frontend:
    build: ./Frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend

volumes:
  mongo-data: 